
import entities.Discipline;
import entities.SchoolClass;
import entities.Student;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import operacoes.CrudDiscipline;
import operacoes.CrudSchoolClass;
import operacoes.CrudStudent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author arthu
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        inserir_alunos3 = new java.awt.Button();
        inserir_alunos4 = new java.awt.Button();
        inserir_alunos5 = new java.awt.Button();
        surname1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_student2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inserir_alunos = new java.awt.Button();
        inserir_alunos1 = new java.awt.Button();
        inserir_alunos2 = new java.awt.Button();
        surname = new javax.swing.JLabel();
        ra_student = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name_student = new javax.swing.JTextField();
        surname_student = new javax.swing.JTextField();
        surname2 = new javax.swing.JLabel();
        dateBirth_student = new javax.swing.JTextField();
        surname3 = new javax.swing.JLabel();
        surname4 = new javax.swing.JLabel();
        city_student1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        insert_turma = new java.awt.Button();
        update_turma = new java.awt.Button();
        delete_turma = new java.awt.Button();
        description = new javax.swing.JLabel();
        nameDiscipline_class = new javax.swing.JTextField();
        nameDis = new javax.swing.JLabel();
        description_class = new javax.swing.JTextField();
        inserir_disciplina_class = new java.awt.Button();

        inserir_alunos3.setActionCommand("update_alunos");
        inserir_alunos3.setLabel("Atualizar");
        inserir_alunos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_alunos3ActionPerformed(evt);
            }
        });

        inserir_alunos4.setActionCommand("inserir_alunos");
        inserir_alunos4.setLabel("Inserir");
        inserir_alunos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_alunos4ActionPerformed(evt);
            }
        });

        inserir_alunos5.setActionCommand("delete_alunos");
        inserir_alunos5.setLabel("Deletar");
        inserir_alunos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_alunos5ActionPerformed(evt);
            }
        });

        surname1.setText("Surname: ");

        jLabel3.setText("Name: ");

        name_student2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_student2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surname1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(inserir_alunos4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(inserir_alunos3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(inserir_alunos5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(name_student2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(417, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inserir_alunos5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserir_alunos4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserir_alunos3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addComponent(surname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(307, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(name_student2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Diciplina", jPanel3);

        inserir_alunos.setActionCommand("update_alunos");
        inserir_alunos.setLabel("Atualizar");
        inserir_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_alunosActionPerformed(evt);
            }
        });

        inserir_alunos1.setActionCommand("inserir_alunos");
        inserir_alunos1.setLabel("Inserir");
        inserir_alunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_alunos1ActionPerformed(evt);
            }
        });

        inserir_alunos2.setActionCommand("delete_alunos");
        inserir_alunos2.setLabel("Deletar");
        inserir_alunos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_alunos2ActionPerformed(evt);
            }
        });

        surname.setText("City: ");

        ra_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra_studentActionPerformed(evt);
            }
        });

        jLabel2.setText("Name: ");

        name_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_studentActionPerformed(evt);
            }
        });

        surname_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname_studentActionPerformed(evt);
            }
        });

        surname2.setText("Surname: ");

        dateBirth_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateBirth_studentActionPerformed(evt);
            }
        });

        surname3.setText("Date Birth");

        surname4.setText("Ra:");

        city_student1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_student1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(inserir_alunos1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(inserir_alunos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(inserir_alunos2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ra_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateBirth_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city_student1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(541, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(name_student, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inserir_alunos2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserir_alunos1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserir_alunos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(surname4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ra_student, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(city_student1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(surname3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surname_student, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateBirth_student, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(373, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(name_student, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(336, Short.MAX_VALUE)))
        );

        inserir_alunos.getAccessibleContext().setAccessibleName("Inserir");

        jTabbedPane1.addTab("Alunos", jPanel2);

        insert_turma.setActionCommand("inserir_alunos");
        insert_turma.setLabel("Inserir");
        insert_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_turmaActionPerformed(evt);
            }
        });

        update_turma.setActionCommand("update_alunos");
        update_turma.setLabel("Atualizar");
        update_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_turmaActionPerformed(evt);
            }
        });

        delete_turma.setActionCommand("delete_alunos");
        delete_turma.setLabel("Deletar");
        delete_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_turmaActionPerformed(evt);
            }
        });

        description.setText("Description:");

        nameDiscipline_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDiscipline_classActionPerformed(evt);
            }
        });

        nameDis.setText("Name Discipline:");

        description_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description_classActionPerformed(evt);
            }
        });

        inserir_disciplina_class.setActionCommand("inserir_alunos");
        inserir_disciplina_class.setLabel("Inserir Disciplina");
        inserir_disciplina_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_disciplina_classActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(insert_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(update_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(description_class, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameDis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameDiscipline_class, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(delete_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(inserir_disciplina_class, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserir_disciplina_class, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDiscipline_class, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description_class, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(292, 292, 292))
        );

        inserir_disciplina_class.getAccessibleContext().setAccessibleName("Inserir Diciplina");

        jTabbedPane1.addTab("Turma", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private CrudDiscipline crud_D = new CrudDiscipline();
    private CrudSchoolClass crud_C = new CrudSchoolClass();
    private CrudStudent crud_S = new CrudStudent();
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    private void inserir_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_alunosActionPerformed
         try{   
        Student student = new Student(name_student.getText(), surname_student.getText(), new java.sql.Date(sdf.parse(dateBirth_student.getText()).getTime()), ra_student.getText());
        crud_S.update(student);
        }
        catch(ParseException e){
            System.out.println("Error date student: " + e.getMessage());
        }
    }//GEN-LAST:event_inserir_alunosActionPerformed

    private void inserir_alunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_alunos1ActionPerformed
        try{   
        Student student = new Student(name_student.getText(), surname_student.getText(), new java.sql.Date(sdf.parse(dateBirth_student.getText()).getTime()), ra_student.getText());
        crud_S.insert(student);
        }
        catch(ParseException e){
            System.out.println("Error date student: " + e.getMessage());
        }
          
    }//GEN-LAST:event_inserir_alunos1ActionPerformed

    private void inserir_alunos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_alunos2ActionPerformed
        String num = ra_student.getText();
        Student deleta = crud_S.findByRa(Integer.parseInt(num));
        crud_S.delete(deleta);
    }//GEN-LAST:event_inserir_alunos2ActionPerformed

    private void ra_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ra_studentActionPerformed

    private void name_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_studentActionPerformed

    private void inserir_alunos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_alunos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserir_alunos3ActionPerformed

    private void inserir_alunos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_alunos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserir_alunos4ActionPerformed

    private void inserir_alunos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_alunos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserir_alunos5ActionPerformed

    private void name_student2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_student2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_student2ActionPerformed

    private void surname_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname_studentActionPerformed

    private void dateBirth_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateBirth_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateBirth_studentActionPerformed

    private void city_student1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_student1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_student1ActionPerformed

    private void insert_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_turmaActionPerformed
        SchoolClass sc = new SchoolClass(description_class.getText());
        crud_C.insert(sc);
    }//GEN-LAST:event_insert_turmaActionPerformed

    private void update_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_turmaActionPerformed
        String name = description_class.getText();
        SchoolClass update = crud_C.findByDescription(name);
        crud_C.update(update);
    }//GEN-LAST:event_update_turmaActionPerformed

    private void delete_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_turmaActionPerformed
        String name = description_class.getText();
        SchoolClass delete = crud_C.findByDescription(name);
        crud_C.delete(delete);
    }//GEN-LAST:event_delete_turmaActionPerformed

    private void nameDiscipline_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDiscipline_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameDiscipline_classActionPerformed

    private void description_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_description_classActionPerformed

    private void inserir_disciplina_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_disciplina_classActionPerformed
        String name = nameDiscipline_class.getText();
        Discipline d = crud_D.findByName(name);
        String name2 = description_class.getText();
        SchoolClass addDis = crud_C.findByDescription(name2);
        addDis.add_discipline(d);
    }//GEN-LAST:event_inserir_disciplina_classActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city_student1;
    private javax.swing.JTextField dateBirth_student;
    private java.awt.Button delete_turma;
    private javax.swing.JLabel description;
    private javax.swing.JTextField description_class;
    private java.awt.Button inserir_alunos;
    private java.awt.Button inserir_alunos1;
    private java.awt.Button inserir_alunos2;
    private java.awt.Button inserir_alunos3;
    private java.awt.Button inserir_alunos4;
    private java.awt.Button inserir_alunos5;
    private java.awt.Button inserir_disciplina_class;
    private java.awt.Button insert_turma;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameDis;
    private javax.swing.JTextField nameDiscipline_class;
    private javax.swing.JTextField name_student;
    private javax.swing.JTextField name_student2;
    private javax.swing.JTextField ra_student;
    private javax.swing.JLabel surname;
    private javax.swing.JLabel surname1;
    private javax.swing.JLabel surname2;
    private javax.swing.JLabel surname3;
    private javax.swing.JLabel surname4;
    private javax.swing.JTextField surname_student;
    private java.awt.Button update_turma;
    // End of variables declaration//GEN-END:variables
}
